apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qagju22ow-nodejs
  janus-idp.io/tekton: qagju22ow-nodejs
  backstage.io/kubernetes-id: qagju22ow-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qagju22ow-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
