apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qagju22ow-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qagju22ow-nodejs 
  name: qagju22ow-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qagju22ow-nodejs 
